### ISSUE TITLE
School Bus doesn't recall the previously save parameters since the last update

### ISSUE THREAD

**Issue by spectromas** [gluethegiant/gtg-rack#2]
Title says it all really, if I open a patch that had School Bus in it and was saved before the latest update then the level is set to zero.

**Comment by gluethegiant** [comment]
Some of the parameters were put into arrays to optimize code during that update (and those parameters didn't load from last version). If I saw the issue sooner I could have created a code work around or at least made an announcement.

The workaround is to reset your levels. Your patch will then save with the new levels, of course.

I'll work on putting something in the README. Current development has been very focused on not changing saved patches.

EDIT: Actually, parameters are saved with an ID based on order. Some were moved since version 1.0.0., not knowing that they weren't saved with a parameter name.

**Comment by gluethegiant** [comment]
I'm looking into a code fix so future releases will load a patch that used v1.0.0.

**Comment by gluethegiant** [comment]
First, thank you for opening the issue! It has been fun to code for VCV Rack, and I'm learning something new every day.

The short of the problem is that parameters are automatically saved based on their order, and I was under the mistaken impression that they were saved based on name. The breakage didn't come from an accidental renaming, it came from moving the order of some parameters and not knowing that would change how the saved patches would be opened.

This system makes it easy to not have an issue like this in the future (I just keep parameters in the same order), but it makes it really difficult to come up with a way to fix the version 1 patches in the next release. I can't just load an old parameter based on an old name.

We'll have to stick with the work around (reset levels and save) and all future code not changing the order of params. I'll also add something to the README.

Have a great one!

**Comment by spectromas** [comment]
That's a shame about the old patches but great to hear that it is now future-proofed. It's actually been good to reset the levels, makes you hear it in a different way than before. 

Thank you for the amazing modules!
