### ISSUE TITLE
Mute/Solo buttons for Road Module

### ISSUE THREAD

**Issue by blackearth2014** [gluethegiant/gtg-rack#3]
Is it possible to get mute and solo buttons on the Road Module for live performance needs and signal checking?

**Comment by gluethegiant** [comment]
I like that request.

Solo (audition) features are in the works right now. The very next release, 1.0.5, has an update to Bus Route that provides a (by) pass button that also auditions (solos) your send effects. Not super handy for live work, but valuable when fine tuning a patch.

Other updates on Bus Depot and Bus Route have live usage in mind (with an improved fader on Bus Depot and some changes that make it easier to think of Bus Depots coming before Bus Route for live use).

Back to your request. I have always thought of a Bus Depot module needed for mix groups, but you are right that even just a mute button (with a pop filter, of course) on each BUS IN of Road would create mix groups without the need of additional Bus Depot modules. Again, I like the idea. I'm mulling over how to add it to the above plans. I think it might come sooner rather than later.

Thank you!

Edit: I fixed a couple of typos. And I said too much.

**Comment by gluethegiant** [comment]
Just wanted to mention that I fixed some typos in my first reply. The short of what I was saying is that I can see the value of adding on buttons with a long click solo option to the Road module. It would also follow the design principles well, keeping the face of the modules more like the real world. Again, thanks for the idea. I would have to use tiny buttons and it's going to be tricky to make it look and work well, but I'm excited to give it a try.

**Comment by blackearth2014** [comment]
Thanks for the reply. I don't know if it is possible but how about developing the port text name as a mute button. Bus IN 1 - Bus IN 6 can be the off/on toggle effect switch. Or double click the out rim of the port itself.

**Comment by blackearth2014** [comment]
I mean double click the ports to solo and the port text name as the mute.

**Comment by gluethegiant** [comment]
Right now I'm implementing long click for audition (solo) on Bus Route sends. My thought is to do the same with Road, have a button with a green light when the BUS IN is on. If you click it it goes off. If you long click it, it will audition that BUS IN (mix group) and temporarily mute any of the other buttons that are on (green) at the time. What do you think of long click to solo?

**Comment by gluethegiant** [comment]
I just pushed the new code for Road. There are now on/audition buttons for each BUS IN. You can use the buttons to easily toggle mixer groups or individual mixers that connect Road. If you hold on a button for just a fraction of a second, you enter audition mode and will audition (solo) that BUS IN while others mute. All of the muting and auditioning is pop free and good for live use.

I still have some work to do on 1.0.5 over the next day or two, but then I'll throw tests at everything, create beta builds, and get ready for the next release. Thank you again for the push to add more functionality to Road. I'm really enjoying it.

**Comment by blackearth2014** [comment]
Thank you for listening to our suggestions.

**Comment by gluethegiant** [comment]
The 1.0.5 release with this enhancement will be available in the VCV Rack Library within the next few days.
